import { useState } from "react";
import { ArrowLeft,Mail,MapPin,User } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { useGlobalContext } from "../../../context/GlobalContext";
import { updateUserProfile } from "../../../api/user.api";
import type { UserUpdateDataType } from "../../../types/user.type";

export default function MyProfile(){
 const{user,updateUser}=useGlobalContext();const navigate=useNavigate();const[editing,setEditing]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[form,setForm]=useState<UserUpdateDataType>({});
 if(!user)return null;
 const updateLocation=(key:string,value:string)=>setForm(x=>({...x,location:{...(x.location??{}),[key]:value}}));
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError("");try{const data=await updateUserProfile(form);updateUser(data.data);setEditing(false)}catch(err:any){setError(err?.response?.data?.message??"Unable to update profile.")}finally{setSaving(false)}};
 return <div className="p-6"><div className="flex items-center gap-3"><button onClick={()=>navigate("/profile")} className="rounded-full p-2 hover:bg-gray-100"><ArrowLeft size={20}/></button><h1 className="text-2xl font-bold">My Profile</h1></div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-600">{error}</p>}{!editing?<div className="mt-8 space-y-4"><div className="rounded-xl border bg-gray-50 p-4"><div className="flex items-center gap-2 text-xs text-gray-400"><User size={16}/>Name</div><p className="mt-2 font-semibold">{user.name}</p></div><div className="rounded-xl border bg-gray-50 p-4"><div className="flex items-center gap-2 text-xs text-gray-400"><Mail size={16}/>Email</div><p className="mt-2 font-semibold">{user.email}</p></div><div className="rounded-xl border bg-gray-50 p-4"><div className="flex items-center gap-2 text-xs text-gray-400"><MapPin size={16}/>Location</div>{user.location?<div className="mt-2 text-sm text-gray-700"><p>{user.location.address}</p><p>{user.location.city}, {user.location.state}</p><p>{user.location.country} - {user.location.pincode}</p></div>:<p className="mt-2 text-sm text-gray-500">No location added</p>}</div><button onClick={()=>{setForm({name:user.name,location:user.location?{...user.location}:undefined});setEditing(true)}} className="w-full rounded-xl bg-gray-900 px-4 py-3 text-sm font-semibold text-white">Edit profile</button></div>:<form onSubmit={submit} className="mt-8 space-y-4"><label className="block text-sm font-medium">Name<input value={form.name??""} onChange={e=>setForm(x=>({...x,name:e.target.value}))} className="mt-1 w-full rounded-xl border px-3 py-2.5" required/></label><div className="rounded-2xl border p-4"><p className="font-semibold">Location</p>{["address","city","state","country","pincode"].map(key=><label key={key} className="mt-3 block text-xs font-medium capitalize text-gray-600">{key}<input value={String((form.location as Record<string,unknown>|undefined)?.[key]??"")} onChange={e=>updateLocation(key,e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"/></label>)}</div><div className="flex gap-2"><button disabled={saving} className="flex-1 rounded-xl bg-gray-900 px-4 py-3 text-sm font-semibold text-white">{saving?"Saving...":"Save changes"}</button><button type="button" onClick={()=>setEditing(false)} className="rounded-xl border px-4 py-3 text-sm font-semibold">Cancel</button></div></form>}</div>
}
